name: CI Pipeline for Spring Petclinic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: spring-petclinic
      REGISTRY: harbor.bluesunnywings.com
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: ./mvnw package -DskipTests

    - name: Run SCA with Trivy (Dependencies)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'json'
        output: 'trivy-sca-results.json'

    - name: Log in to Harbor registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:latest

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Sign container image
      run: |
        cosign sign --yes ${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        cosign sign --yes ${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:latest

    - name: Run Trivy image vulnerability scanner (JSON)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'json'
        output: 'trivy-image-results.json'

    - name: Run Trivy image vulnerability scanner (SARIF)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'sarif'
        output: 'trivy-image-results.sarif'

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-scan-results
        path: |
          trivy-sca-results.json
          trivy-image-results.json
          trivy-image-results.sarif
        retention-days: 30

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-image-results.sarif'

    - name: Update K8s manifest with new image tag
      run: |
        sed -i "s|harbor.bluesunnywings.com/library/spring-petclinic:.*|harbor.bluesunnywings.com/library/spring-petclinic:${{ github.sha }}|g" k8s/petclinic.yml
        
    - name: Commit and push updated manifest
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/petclinic.yml
        git commit -m "Update image tag to ${{ github.sha }}" || exit 0
        git push
